CREATE TABLE hockeymatch (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	home VARCHAR(255) NOT NULL,
	away VARCHAR(255) NOT NULL,
	home_goals SMALLINT NOT NULL,
	away_goals SMALLINT NOT NULL,
	overtime BOOLEAN NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
